<!DOCTYPE html>
<html>
<head>
    <title>Folder Report - {{ $folder->folder_name }}</title>
    <style>
        body { font-family: 'DejaVu Sans', sans-serif; line-height: 1.6; }
        .header { text-align: center; margin-bottom: 30px; }
        .section { margin-bottom: 25px; }
        .section-title { 
            color: #2c5282; 
            border-bottom: 2px solid #2c5282;
            padding-bottom: 5px;
            margin-bottom: 15px;
        }
        .info-table { width: 100%; margin-bottom: 25px; }
        .info-table td { padding: 8px; vertical-align: top; }
        .info-table td:first-child { 
            width: 30%; 
            font-weight: bold;
            color: #4a5568;
        }
        .report-table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 15px;
        }
        .report-table th,
        .report-table td {
            border: 1px solid #cbd5e0;
            padding: 10px;
            text-align: left;
        }
        .report-table th {
            background-color: #f7fafc;
            color: #4a5568;
        }
        .footer {
            text-align: center;
            margin-top: 30px;
            color: #718096;
            font-size: 0.9em;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $folder->folder_name }}'s Folder Report</h1>
        <p>Generated: {{ now()->format('d/m/Y H:i') }}</p>
    </div>

    <div class="section">
        <h2 class="section-title">Personal Information</h2>
        <table class="info-table">
            <tr>
                <td>User ID:</td>
                <td>{{ $folder->user_id }}</td>
            </tr>
            <tr>
                <td>Birth Date:</td>
                <td>{{ \Carbon\Carbon::parse($folder->birth_date)->format('d/m/Y') }}</td>
            </tr>
            <tr>
                <td>Phone Number:</td>
                <td>{{ $folder->phone_number }}</td>
            </tr>
            <tr>
                <td>Address:</td>
                <td>{{ $folder->full_address ?? 'N/A' }}</td>
            </tr>
            <tr>
                <td>Region:</td>
                <td>{{ $folder->region ?? 'N/A' }}</td>
            </tr>
        </table>
    </div>

    <div class="section">
        <h2 class="section-title">Education Information</h2>
        <table class="info-table">
            <tr>
                <td>Education Level:</td>
                <td>{{ $folder->education_level ?? 'N/A' }}</td>
            </tr>
            <tr>
                <td>Start Date:</td>
                <td>{{ $folder->start_date ? \Carbon\Carbon::parse($folder->start_date)->format('d/m/Y') : 'N/A' }}</td>
            </tr>
        </table>
    </div>

    <div class="section">
        <h2 class="section-title">Family Information</h2>
        <table class="info-table">
            <tr>
                <td>Family Members:</td>
                <td>{{ $folder->family_number ?? 'N/A' }}</td>
            </tr>
            <tr>
                <td>Total Siblings:</td>
                <td>{{ $folder->total_siblings ?? 'N/A' }}</td>
            </tr>
            <tr>
                <td>Sibling Position:</td>
                <td>{{ $folder->sibling_position ?? 'N/A' }}</td>
            </tr>
        </table>
    </div>

    <div class="section">
        <h2 class="section-title">Reports</h2>
        @if($folder->reports->count() > 0)
            <table class="report-table">
                <thead>
                    <tr>
                        <th>Date</th>
                        <th>Message</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($folder->reports as $report)
                    <tr>
                        <td>{{ \Carbon\Carbon::parse($report->date)->format('d/m/Y') }}</td>
                        <td>{{ $report->message }}</td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        @else
            <p>No reports available for this folder.</p>
        @endif
    </div>

    <div class="footer">
        <p>Generated by Family Counseling System</p>
        <p>Page <span class="page-number"></span></p>
    </div>
</body>
</html>